#!/usr/bin/env bash

rofi_command="rofi -dmenu $@"

readonly OPTION_POWER="Power"
readonly OPTION_SCAN="Scan"
readonly OPTION_PAIRABLE="Pairable"
readonly OPTION_DISCOVERABLE="Discoverable"
readonly OPTION_DIVIDER="-----------------------"
readonly OPTION_EXIT="Exit"
readonly OPTION_BACK="Back"

readonly DEVICE_PROPERTY_CONNECTED="Connected"
readonly DEVICE_PROPERTY_PAIRED="Paired"
readonly DEVICE_PROPERTY_TRUSTED="Trusted"

get_available_devices() {
    mapfile -t devices < <(bluetoothctl devices | cut -d' ' -f3-)
}

get_property_state_string() {
    local property="$1"
    local expected_string

    case "$property" in
        "$OPTION_POWER")
            expected_string="PowerState: on"
            ;;
        "$OPTION_SCAN")
            expected_string="Discovering: yes"
            ;;
        "$OPTION_PAIRABLE")
            expected_string="Pairable: yes"
            ;;
        "$OPTION_DISCOVERABLE")
            expected_string="Discoverable: yes"
            ;;
        *)
            return 1
            ;;
    esac

    if bluetoothctl show | grep -q "$expected_string"; then
        echo "$property: on"
    else
        echo "$property: off"
    fi
}

get_device_property_state_string() {
    # paired/connected/trusted/blocked
    local mac="$1"
    local property="$2"

    [[ -z "$mac" ]] && return 1
    [[ -z "$property" ]] && return 1

    if bluetoothctl info $mac | grep -q "$property: yes"; then
        echo "$property: yes"
    else
        echo "$property: no"
    fi
}

get_mac_address() {
    local device_name="$1"
    [[ -z "$device_name" ]] && return 1

    bluetoothctl devices | grep -F "$device_name" | cut -d' ' -f2
}

open_device_menu() {
    local device_name=$1
    [[ -z "$device_name" ]] && return 1

    local mac_address="$(get_mac_address "$device_name")"
    [[ -z "$mac_address" ]] && return 1

    local rofi_options=()
    rofi_options+=("$(get_device_property_state_string $mac_address $DEVICE_PROPERTY_CONNECTED)")
    rofi_options+=("$(get_device_property_state_string $mac_address $DEVICE_PROPERTY_PAIRED)")
    rofi_options+=("$(get_device_property_state_string $mac_address $DEVICE_PROPERTY_TRUSTED)")
    rofi_options+=("$OPTION_DIVIDER")
    rofi_options+=("$OPTION_BACK")
    rofi_options+=("$OPTION_EXIT")

    local choice=$(printf '%s\n' "${rofi_options[@]}" | ${rofi_command} -p "$device_name")

    case "$choice" in
        "$DEVICE_PROPERTY_CONNECTED: yes")
            echo "connected -> no"
            open_device_menu "$device_name"
            ;;
        "$DEVICE_PROPERTY_CONNECTED: no")
            echo "connected -> yes"
            open_device_menu "$device_name"
            ;;
        "$DEVICE_PROPERTY_PAIRED: yes")
            echo "paired -> no"
            open_device_menu "$device_name"
            ;;
        "$DEVICE_PROPERTY_PAIRED: no")
            echo "paired -> yes"
            open_device_menu "$device_name"
            ;;
        "$DEVICE_PROPERTY_TRUSTED: yes")
            echo "trusted -> no"
            open_device_menu "$device_name"
            ;;
        "$DEVICE_PROPERTY_TRUSTED: no")
            echo "trusted -> yes"
            open_device_menu "$device_name"
            ;;
        "$OPTION_BACK")
            open_main_menu
            ;;
        "$OPTION_EXIT")
            exit 0
            ;;
        *)
            exit 1
            ;;
    esac
}

open_main_menu() {
    local rofi_options=()

    local power_state=$(get_property_state_string "$OPTION_POWER")
    if [[ "$power_state" == "$OPTION_POWER: on" ]]; then
        devices=()
        get_available_devices devices
        if (( ${#devices[@]} > 0 )); then
            devices+=("$OPTION_DIVIDER")
        fi
        rofi_options+=("${devices[@]}")

        rofi_options+=("$power_state")

        rofi_options+=(
            "$(get_property_state_string "$OPTION_SCAN")"
            "$(get_property_state_string "$OPTION_PAIRABLE")"
            "$(get_property_state_string "$OPTION_DISCOVERABLE")"
        )
    else
        rofi_options+=("$power_state")
    fi
    rofi_options+=("$OPTION_EXIT")

    local choice=$(printf '%s\n' "${rofi_options[@]}" | ${rofi_command} -p "Bluetooth")

    case "$choice" in
        "$OPTION_POWER: on")
            bluetoothctl power off
            ;;
        "$OPTION_POWER: off")
            bluetoothctl power on
            ;;
        "$OPTION_SCAN: off")
            bluetoothctl --timeout 5 scan on
            open_main_menu
            ;;
        "$OPTION_PAIRABLE: on")
            bluetoothctl pairable off
            ;;
        "$OPTION_PAIRABLE: off")
            bluetoothctl pairable on
            ;;
        "$OPTION_DISCOVERABLE: on")
            bluetoothctl discoverable off
            echo "Discoverable -> off"
            ;;
        "$OPTION_DISCOVERABLE: off")
            bluetoothctl discoverable on
            ;;
        "$OPTION_EXIT")
            exit 0
            ;;
        *)
            [[ -z "$choice" ]] && return 1

            open_device_menu "$choice"
            exit 0
            ;;
    esac
}

open_main_menu
