#!/usr/bin/env bash

rofi_command="rofi -dmenu $@"

readonly CONTROLLER_PROPERTY_POWER="Power"
readonly CONTROLLER_PROPERTY_SCAN="Scan"
readonly CONTROLLER_PROPERTY_PAIRABLE="Pairable"
readonly CONTROLLER_PROPERTY_DISCOVERABLE="Discoverable"

readonly DEVICE_PROPERTY_CONNECTED="Connected"
readonly DEVICE_PROPERTY_PAIRED="Paired"
readonly DEVICE_PROPERTY_TRUSTED="Trusted"
readonly DEVICE_OPTION_REMOVE="Remove"

readonly OPTION_DIVIDER="----------------"
readonly OPTION_EXIT="Exit"
readonly OPTION_BACK="Back"

declare -A devices

get_available_devices() {
    devices=()

    local line mac name
    while IFS= read -r line; do
        mac="$(cut -d' ' -f2 <<< "$line")"
        name="$(cut -d' ' -f3- <<< "$line")"
        devices["$mac"]="$name"
    done < <(bluetoothctl devices)
}

get_property_state_string() {
    local property="$1"
    local expected_string

    case "$property" in
        "$CONTROLLER_PROPERTY_POWER")
            expected_string="PowerState: on"
            ;;
        "$CONTROLLER_PROPERTY_SCAN")
            expected_string="Discovering: yes"
            ;;
        "$CONTROLLER_PROPERTY_PAIRABLE")
            expected_string="Pairable: yes"
            ;;
        "$CONTROLLER_PROPERTY_DISCOVERABLE")
            expected_string="Discoverable: yes"
            ;;
        *)
            return 1
            ;;
    esac

    if bluetoothctl show | grep -q "$expected_string"; then
        echo "$property: on"
    else
        echo "$property: off"
    fi
}

get_device_property_state_string() {
    # paired/connected/trusted/blocked
    local mac="$1"
    local property="$2"

    [[ -z "$mac" ]] && return 1
    [[ -z "$property" ]] && return 1

    if bluetoothctl info "$mac" | grep -q "$property: yes"; then
        echo "$property: yes"
    else
        echo "$property: no"
    fi
}

get_mac_address() {
    local target_name="$1"
    local mac

    for mac in "${!devices[@]}"; do
        if [[ "${devices[$mac]}" == "$target_name" ]]; then
            echo "$mac"
            return 0
        fi
    done

    return 1
}

open_device_menu() {
    local mac_address="$1"
    [[ -z "$mac_address" ]] && return 1

    local device_name="${devices[$mac_address]}"

    local rofi_options=()
    rofi_options+=("$(get_device_property_state_string "$mac_address" "$DEVICE_PROPERTY_CONNECTED")")
    rofi_options+=("$(get_device_property_state_string "$mac_address" "$DEVICE_PROPERTY_PAIRED")")
    rofi_options+=("$(get_device_property_state_string "$mac_address" "$DEVICE_PROPERTY_TRUSTED")")
    rofi_options+=("$DEVICE_OPTION_REMOVE")
    rofi_options+=("$OPTION_DIVIDER")
    rofi_options+=("$OPTION_BACK")
    rofi_options+=("$OPTION_EXIT")

    local prompt
    if [[ "${device_name//[-:]/}" == "${mac_address//[-:]/}" ]]; then
        prompt="$mac_address"
    else
        prompt="$device_name ($mac_address)"
    fi
    local choice=$(printf '%s\n' "${rofi_options[@]}" | ${rofi_command} -p "$prompt")

    case "$choice" in
        "$DEVICE_PROPERTY_CONNECTED: yes")
            bluetoothctl disconnect "$mac_address"
            open_device_menu "$mac_address"
            ;;
        "$DEVICE_PROPERTY_CONNECTED: no")
            bluetoothctl connect "$mac_address"
            open_device_menu "$mac_address"
            ;;
        "$DEVICE_PROPERTY_PAIRED: yes")
            bluetoothctl unpair "$mac_address"
            open_device_menu "$mac_address"
            ;;
        "$DEVICE_PROPERTY_PAIRED: no")
            bluetoothctl pair "$mac_address"
            open_device_menu "$mac_address"
            ;;
        "$DEVICE_PROPERTY_TRUSTED: yes")
            bluetoothctl untrust "$mac_address"
            open_device_menu "$mac_address"
            ;;
        "$DEVICE_PROPERTY_TRUSTED: no")
            bluetoothctl trust "$mac_address"
            open_device_menu "$mac_address"
            ;;
        "$DEVICE_OPTION_REMOVE")
            bluetoothctl remove "$mac_address"
            open_main_menu
            ;;
        "$OPTION_BACK")
            open_main_menu
            ;;
        "$OPTION_EXIT")
            exit 0
            ;;
        *)
            exit 1
            ;;
    esac
}

open_main_menu() {
    local rofi_options=()

    local power_state=$(get_property_state_string "$CONTROLLER_PROPERTY_POWER")
    if [[ "$power_state" == "$CONTROLLER_PROPERTY_POWER: on" ]]; then
        get_available_devices
        if (( ${#devices[@]} > 0 )); then
            rofi_options+=("${devices[@]}")
            rofi_options+=("$OPTION_DIVIDER")
        fi

        rofi_options+=("$power_state")

        rofi_options+=(
            "$(get_property_state_string "$CONTROLLER_PROPERTY_PAIRABLE")"
            "$(get_property_state_string "$CONTROLLER_PROPERTY_DISCOVERABLE")"
            "$CONTROLLER_PROPERTY_SCAN"
            "$OPTION_DIVIDER"
        )
    else
        rofi_options+=("$power_state")
    fi

    rofi_options+=("$OPTION_EXIT")

    local choice=$(printf '%s\n' "${rofi_options[@]}" | ${rofi_command} -p "Bluetooth")

    case "$choice" in
        "$CONTROLLER_PROPERTY_POWER: on")
            bluetoothctl power off
            ;;
        "$CONTROLLER_PROPERTY_POWER: off")
            bluetoothctl power on
            ;;
        "$CONTROLLER_PROPERTY_SCAN")
            bluetoothctl --timeout 5 scan on
            open_main_menu
            ;;
        "$CONTROLLER_PROPERTY_PAIRABLE: on")
            bluetoothctl pairable off
            ;;
        "$CONTROLLER_PROPERTY_PAIRABLE: off")
            bluetoothctl pairable on
            ;;
        "$CONTROLLER_PROPERTY_DISCOVERABLE: on")
            bluetoothctl discoverable off
            echo "Discoverable -> off"
            ;;
        "$CONTROLLER_PROPERTY_DISCOVERABLE: off")
            bluetoothctl discoverable on
            ;;
        "$OPTION_EXIT")
            exit 0
            ;;
        *)
            [[ -z "$choice" ]] && return 1

            open_device_menu "$(get_mac_address "$choice")"
            exit 0
            ;;
    esac
}

open_main_menu
